# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- main
 
pool: AnupmaK

 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UiPathTest@5
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Token_check'
    testSet: 'yu'
    folderName: 'anupma'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output.xml'
    traceLevel: 'Verbose'
    attachRobotLogs: true
    additionalArguments: '--headers "Accept=application/json;Content-Type=application/json"'