# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- main
 
pool: AnupmaK
 
 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@5
  inputs:
    cliVersion: 'WIN_24.12.9166.24491'
    cliNupkgPath: '"D:\test_project\nupkg"'
- task: UiPathTest@5
  inputs:
    orchestratorConnection: 'new_uipath1'
    testTarget: 'TestSet'
    testSet: 'yu'
    folderName: 'anupma'
    testReportDestination: 'output/result'
    attachRobotLogs: true
    enablePackageMetadata: true