# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- main
 
pool: AnupmaK
 
 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@5
  inputs:
    cliVersion: 'WIN_24.12.9166.24491'
- task: UiPathTest@5
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath Orch'
    testSet: 'yu'
    folderName: 'anupma'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'
    attachRobotLogs: true
- task: UiPathPack@5
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    outputType: 'Tests'
    orchestratorConnection: 'Uipath Orch'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'